class WordData {
  WordData._();

  static const Map<String, List<String>> categories = {
    'Hayvanlar': [
      'ASLAN',
      'KAPLAN',
      'KARTAL',
      'BALIK',
      'KURT',
      'KEDİ',
      'FARE',
      'LEYLEK',
      'TURNA',
      'ÖRDEK',
      'TAVUK',
      'KARGA',
      'TİLKİ',
      'TAVŞAN',
    ],
    'Şehirler': [
      'ANKARA',
      'BURSA',
      'KONYA',
      'ADANA',
      'BOLU',
      'ORDU',
      'TOKAT',
      'HATAY',
      'RİZE',
      'NİĞDE',
      'SAMSUN',
      'SİNOP',
      'DÜZCE',
    ],
    'Meslekler': [
      'DOKTOR',
      'AVUKAT',
      'KASAP',
      'TERZİ',
      'GARSON',
      'BERBER',
      'ECZACI',
      'KAPTAN',
      'MİMAR',
      'HAKİM',
      'PİLOT',
      'AŞÇI',
    ],
    'Yiyecekler': [
      'ELMA',
      'BÖREK',
      'KEBAP',
      'PİDE',
      'AYRAN',
      'SUCUK',
      'SİMİT',
      'DOLMA',
      'CACIK',
      'CORBA',
      'EKMEK',
      'HELVA',
    ],
    'Doğa': [
      'ORMAN',
      'DENİZ',
      'BULUT',
      'NEHIR',
      'GÖLET',
      'TOPRAK',
      'YILDIZ',
      'GÜNEŞ',
      'ÇIMEN',
    ],
    'Spor': [
      'FUTBOL',
      'TENİS',
      'YÜZME',
      'GÜREŞ',
      'KOŞU',
      'BOKS',
      'KAYAK',
      'OKÇULUK',
    ],
    'Renkler': [
      'KIRMIZI',
      'MAVİ',
      'YEŞİL',
      'SARI',
      'BEYAZ',
      'SİYAH',
      'MOR',
      'TURUNCU',
      'PEMBE',
      'GRİ',
    ],
    'Ülkeler': [
      'ALMANYA',
      'FRANSA',
      'MISIR',
      'KANADA',
      'BREZİLYA',
      'RUSYA',
      'ÇİN',
      'KORE',
      'KÜBA',
      'İRAN',
    ],
    'Bilim': [
      'ATOM',
      'HÜCRE',
      'GEN',
      'DENEY',
      'KÜTLE',
      'PROTON',
      'PLAZMA',
      'FOTON',
      'ENERJİ',
    ],
    'Müzik': [
      'GİTAR',
      'KEMAN',
      'DAVUL',
      'PİYANO',
      'FLÜT',
      'NOTA',
      'BESTE',
      'KORO',
      'MAKAM',
    ],
  };

  /// Izgara boşluklarını doldurmak için Türkçe alfabe
  static const String turkishAlphabet = 'ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZ';
}
